version: '3.7'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
  app:
    image: acim/go-reflex
    container_name: app
    depends_on:
      - redis
    volumes:
      - ./:/app